# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer una carpeta de trabajo
WORKDIR /app

# Copiar el archivo de requerimientos y instalar las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Ejecutar tu aplicación cuando el contenedor se inicie
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
